### ISSUE TITLE
Device provisioning clarifications

### ISSUE THREAD

**Issue by Necrokefalos** [FIWARE/tutorials.IoT-Agent-JSON#4]
Hello, i am currently using IoT-Agent-Json and Orion-LD with timescaleDB.
I would like you to clarify few things if possible.
1) On device provisioning what's the best practice to define the coordinates for a static device in json format in order to send it to iot-agent-json?
Here is how i did it.
```
{
  "device_id": "temperature003",
  "entity_name": "urn:ngsi-ld:Device:temperature003",
  "timezone": "Europe/Athens",
  "attributes": [
    {
      "object_id": "t",
      "name": "temperature",
      "type": "Property",
      "metadata": {
        "unitCode": {
          "type": "Float",
          "value": "CEL"
        }
      }
    },
    {
      "object_id": "w",
      "name": "wind",
      "type": "Property",
      "metadata": {
        "unitCode": {
          "type": "Float",
          "value": "M/S"
        }
      }
    }
  ],
  "static_attributes": [
    {
      "name": "controlledAsset",
      "type": "Relationship",
      "value": "urn:ngsi-ld:Building:uni001"
    },
    {
      "name": "location",
      "type": "GeoProperty",
      "value": {
        "type": "Point",
        "coordinates": [
          23.7183,
          37.9592
        ]
      }
    }
  ]
}
```
2) I took a look inside of timescaleDB in attributes table and i saw that attribute `location` doesn't have a proper id like the rest of attributes.
![image](https://user-images.githubusercontent.com/32498688/139433856-aa02b67c-27f1-4e90-b9a1-6b10f0fdfb5a.png)
Why and how can i fix this to be like `https://.../location`?

**Comment by jason-fox** [comment]
`location` is defined in the default-core `@context` of the [NGSI-LD specification](https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.04.01_60/gs_cim009v010401p.pdf) and is never expanded within an NGSI-LD request, `wind` and `controlledAsset` are not part of the NGSI-LD API and fall to the default context if not defined elsewhere.

If you look in the [ngsi-ld-core-context.jsonld](https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.4.jsonld) you will see `location` is defined in the list of terms and the final `@vocab` statement pushes unknown terms to the default context:

```json
{
  "@context": {
    "ngsi-ld": "https://uri.etsi.org/ngsi-ld/",
    "geojson": "https://purl.org/geojson/vocab#",
    "id": "@id",
    "type": "@type",
...
    "location": "ngsi-ld:location",
...
    "@vocab": "https://uri.etsi.org/ngsi-ld/default-context/"
  }
}
```

I assume that you have provisioned your IoT Agent using the core context

```text
- IOTA_CB_NGSI_VERSION=ld 
- IOTA_JSON_LD_CONTEXT=https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.4.jsonld
```

This is incorrect and unnecessary as the default context is assumed in all NGSI-LD calls, what  you need to do is to [generate your own `@context` file](https://ngsi-ld-tutorials.readthedocs.io/en/latest/understanding-%40context.html)  holding all the terms defined in your entities and pass that into the IoT Agent.

```text
- IOTA_CB_NGSI_VERSION=ld 
- IOTA_JSON_LD_CONTEXT=http://some/public/ngsi-context.jsonld
```

Your own  `@context` file maps the terminology you currently use (like `wind` or `controlledAsset` to an agreed set of IRIs (not necessarily URLs) so someone else may use different "short names" within their system. 

The result of adding linked data concepts to NGSI is that all defined terms can be sent as either expanded or compacted or altered as necessary depending upon the Linked `@context` header sent when making a request.  However core keywords such as `location` will never be expanded when making NGSI-LD requests (since the core `@context` is assumed) but could be transformed to JSON-LD by an additional operation.

**Comment by Necrokefalos** [comment]
Thanks for the explanation and links you provided, i managed to create my context file, they were really helpful!
